# Generated by Django 3.0.8 on 2020-08-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.png', upload_to='recipe'),
        ),
    ]
